#include <iostream>

const long delay = 10000000L;

int main() {
	int tic;
	std::cout << "\nHow often should the tone be output?";
	std::cin >> tic;

	do {  //Since a do-while statement is used, the program outputs a tone even if the user types 0 or a negative number.
		for (long i = 0; i < delay; i++);
		std::cout << "Now the tone!\a" << std::endl; 
		/*Text and a tone are subsequently output. The tone is generated by outputting the
control character BELL (ASCII code 7), which is represented by the escape sequence \a.*/
	} while (--tic > 0);
	std::cout << "End of the acoustic interlude!\n";
	return 0;
}